// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crps_cpp
arma::rowvec crps_cpp(arma::rowvec y, arma::mat x);
RcppExport SEXP _eppverification_crps_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// crps_sml_cpp
arma::rowvec crps_sml_cpp(arma::rowvec y, arma::mat x);
RcppExport SEXP _eppverification_crps_sml_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_sml_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// crps_mc_cpp
arma::rowvec crps_mc_cpp(arma::rowvec y, arma::mat x);
RcppExport SEXP _eppverification_crps_mc_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_mc_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// euclnorm_cpp
double euclnorm_cpp(arma::rowvec x);
RcppExport SEXP _eppverification_euclnorm_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(euclnorm_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// es_cpp
arma::rowvec es_cpp(arma::mat y, arma::cube x);
RcppExport SEXP _eppverification_es_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(es_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// es_mc_cpp
arma::rowvec es_mc_cpp(arma::mat y, arma::cube x);
RcppExport SEXP _eppverification_es_mc_cpp(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(es_mc_cpp(y, x));
    return rcpp_result_gen;
END_RCPP
}
// vs_cpp
arma::rowvec vs_cpp(arma::mat y, arma::cube x, arma::mat w, double p);
RcppExport SEXP _eppverification_vs_cpp(SEXP ySEXP, SEXP xSEXP, SEXP wSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vs_cpp(y, x, w, p));
    return rcpp_result_gen;
END_RCPP
}
// ds_cpp
arma::rowvec ds_cpp(arma::cube x);
RcppExport SEXP _eppverification_ds_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ds_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eppverification_crps_cpp", (DL_FUNC) &_eppverification_crps_cpp, 2},
    {"_eppverification_crps_sml_cpp", (DL_FUNC) &_eppverification_crps_sml_cpp, 2},
    {"_eppverification_crps_mc_cpp", (DL_FUNC) &_eppverification_crps_mc_cpp, 2},
    {"_eppverification_euclnorm_cpp", (DL_FUNC) &_eppverification_euclnorm_cpp, 1},
    {"_eppverification_es_cpp", (DL_FUNC) &_eppverification_es_cpp, 2},
    {"_eppverification_es_mc_cpp", (DL_FUNC) &_eppverification_es_mc_cpp, 2},
    {"_eppverification_vs_cpp", (DL_FUNC) &_eppverification_vs_cpp, 4},
    {"_eppverification_ds_cpp", (DL_FUNC) &_eppverification_ds_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_eppverification(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
