# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crps_cpp <- function(y, x) {
    .Call(`_eppverification_crps_cpp`, y, x)
}

crps_sml_cpp <- function(y, x) {
    .Call(`_eppverification_crps_sml_cpp`, y, x)
}

crps_mc_cpp <- function(y, x) {
    .Call(`_eppverification_crps_mc_cpp`, y, x)
}

euclnorm_cpp <- function(x) {
    .Call(`_eppverification_euclnorm_cpp`, x)
}

es_cpp <- function(y, x) {
    .Call(`_eppverification_es_cpp`, y, x)
}

es_mc_cpp <- function(y, x) {
    .Call(`_eppverification_es_mc_cpp`, y, x)
}

vs_cpp <- function(y, x, w, p) {
    .Call(`_eppverification_vs_cpp`, y, x, w, p)
}

ds_cpp <- function(x) {
    .Call(`_eppverification_ds_cpp`, x)
}

